### ISSUE TITLE
Script for patching the apk

### ISSUE THREAD

**Issue by pizzaso** [Eltion/Facebook-SSL-Pinning-Bypass#1]
Hi @Eltion,

Can you please provide the script for patching the apk if possible?

**Comment by Eltion** [comment]
Hi @pizzaso 
I've created a new branch which includes the patch script here: [patch_script](https://github.com/Eltion/Facebook-SSL-Pinning-Bypass/tree/patch_script).  
The script is quite the same as for instagram, but there is a difference for `x86` and `armeabi-v7a` because native libs that are used have the dynamic relocation section packed and such encoding is currently not supported from [lief-project](https://github.com/lief-project/LIEF).  

There is an open issue about that here: https://github.com/lief-project/LIEF/issues/111 , and also a branch with some implementation of this feature [android-packed-relocations](https://github.com/lief-project/LIEF/tree/android-packed-relocations)

For know I've uploaded the unpacked version of `x86` and `armeabi-v7a` in https://github.com/Eltion/Facebook-SSL-Pinning-Bypass/tree/patch_script/lib which are used by the script to be able to patch also these versions.

For `arm64-v8a` the process is the same as in the instagram library.

**Comment by pizzaso** [comment]
Thank you 🙌 !

**Comment by Eltion** [comment]
No problem 😉. I will leave this on a different branch until I create a script to patch for `x86` and `armeabi-v7a` without manually unpacking relocation from the so file.
