### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by nguyentuan3691** [Eltion/Facebook-SSL-Pinning-Bypass#6]
When run "frida -U -l E:\LD1\LD1\bypassSSL.js -f com.facebook.katana --no-pause"
then show
     ____
    / _  |   Frida 15.2.2 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to VOG-AL00 (id=127.0.0.1:5557)
Spawning `com.facebook.katana`...
[*][*] Waiting for library...
Spawned `com.facebook.katana`. Resuming main thread!
[VOG-AL00::com.facebook.katana ]-> TypeError: cannot set property 'implementation' of undefined
    at <anonymous> (/frida/repl-2.js:77)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:12)
    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250)
    at <anonymous> (frida/node_modules/frida-java-bridge/index.js:242)
    at apply (native)
    at ne (frida/node_modules/frida-java-bridge/lib/class-factory.js:620)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/class-factory.js:598)
Process terminated
[VOG-AL00::com.facebook.katana ]->

how to fix this problem?

**Comment by Eltion** [comment]
It looks like it failed to find `checkTrustedRecursive` function. I added a check to see if the function exist first before trying hook the function. ae38a110e335bda8eb00705db3c9f60b92c71abe

**Comment by yagamicell** [comment]
not working .. conection lost.. and cant login to facebook ..
```
[google Pixel 2::com.facebook.katana ]-> %resume
[google Pixel 2::com.facebook.katana ]-> [*][+] Hooked checkTrustedRecursive
[*][+] Found libliger-native.so at: 0x702a2d969000
[*][+] Hooked function: _ZN8proxygen15SSLVerification17verifyWithMetricsEbP17x509_store_ctx_stRKNSt6__ndk212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS0_31SSLFailureVerificationCallbacksEPNS0_31SSLSuccessVerificationCallbacksERKNS_15TimeUtilGenericINS3_6chrono12steady_clockEEERNS_10TraceEventE
```

**Comment by Eltion** [comment]
@yagamicell  hi there :) . I just tested and login is working for me. Please specify what proxy you're using and show some logs from the proxy.

**Comment by yagamicell** [comment]
> @yagamicell hi there :) . I just tested and login is working for me. Please specify what proxy you're using and show some logs from the proxy.

15:53:35:5492 !SecureClientPipeDirect failed: System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. < The client and server cannot communicate, because they do not possess a common algorithm for pipe (CN=*.facebook.com, O=DO_NOT_TRUST_BC, OU=Created by http://www.fiddler2.com).
15:53:35:8480 !SecureClientPipeDirect failed: System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. < The client and server cannot communicate, because they do not possess a common algorithm for pipe (CN=*.facebook.com, O=DO_NOT_TRUST_BC, OU=Created by http://www.fiddler2.com).
15:53:35:9920 !SecureClientPipeDirect failed: System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. < The client and server cannot communicate, because they do not possess a common algorithm for pipe (CN=*.facebook.com, O=DO_NOT_TRUST_BC, OU=Created by http://www.fiddler2.com).
15:53:36:1849 !SecureClientPipeDirect failed: System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. < The client and server cannot communicate, because they do not possess a common algorithm for pipe (CN=*.facebook.com, O=DO_NOT_TRUST_BC, OU=Created by http://www.fiddler2.com).
15:53:36:3074 !SecureClientPipeDirect failed: System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. < The client and server cannot communicate, because they do not possess a common algorithm for pipe (CN=*.facebook.com, O=DO_NOT_TRUST_BC, OU=Created by http://www.fiddler2.com).
15:53:36:5230 !SecureClientPipeDirect failed: System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. < The client and server cannot communicate, because they do not possess a common algorithm for pipe (CN=*.facebook.com, O=DO_NOT_TRUST_BC, OU=Created by http://www.fiddler2.com).
15:53:36:6934 !SecureClientPipeDirect failed: System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. < The client and server cannot communicate, because they do not possess a common algorithm for pipe (CN=*.facebook.com, O=DO_NOT_TRUST_BC, OU=Created by http://www.fiddler2.com).
15:53:38:6100 !SecureClientPipeDirect failed: System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. < An unknown error occurred while processing the certificate for pipe (CN=*.facebook.com, O=DO_NOT_TRUST_BC, OU=Created by http://www.fiddler2.com).
15:53:38:7167 !SecureClientPipeDirect failed: System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. < An unknown error occurred while processing the certificate for pipe (CN=*.facebook.com, O=DO_NOT_TRUST_BC, OU=Created by http://www.fiddler2.com).
15:53:38:8442 !SecureClientPipeDirect failed: System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. < An unknown error occurred while processing the certificate for pipe (CN=*.facebook.com, O=DO_NOT_TRUST_BC, OU=Created by http://www.fiddler2.com).
15:53:38:9882 !SecureClientPipeDirect failed: System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. < An unknown error occurred while processing the certificate for pipe (CN=*.facebook.com, O=DO_NOT_TRUST_BC, OU=Created by http://www.fiddler2.com).

**Comment by Eltion** [comment]
This looks like a problem with the fiddler proxy. You need a proxy that supports  TLSv1.3. Try using latest version of brup or mitmproxy. Meta apps now only support TLSv1.3

**Comment by yagamicell** [comment]
> This looks like a problem with the fiddler proxy. You need a proxy that supports TLSv1.3. Try using latest version of brup or mitmproxy. Meta apps now only support TLSv1.3

ok thanks for you reply.. i try later..
